name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest     
    steps:
    
    #- name: Checkout
    - uses: actions/checkout@v2.4.2
    - run: npm install
    - run: npm start &

    #- name: Cypress
    - uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress
    - run: npm install
    - run: npm run cypress-e2e
 


