name: Cypress Tests2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    types: ["opened", "synchronize"]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          start: npm run start

      - name: Cypress run
        uses: rmhiguerey/cypress@main
        timeout-minutes: 30
        with:
          start: npm run cypress-e2e
          wait-on: 'http://localhost:3000'
