name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest
    steps:
    
    #- name: Checkout
    - uses: actions/checkout@v2.4.2
    - run: npm install
    - run: npm start&
    
    #- name: Checkout Cypress
    - uses: actions/checkout@main
      with: 
         repository: rmhiguerey/cypress

    #- name: Cypress
    - uses: cypress-io/github-action@v2.9.7
      with:
        browser: chrome
        headless: true
        config-file: cypress.json
        


