name: Cypress Tests2

on: [push]
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - run: npm install
      - run: npm start
     

     
