name: Cypress Tests2

on: [push]
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      
      - name: Checkout
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress

      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 30
        with:
          project: ./rmhiguerey/cypress
          browser: chrome
          headless: true
          # we have already installed all dependencies above
          install: true
          start: ./node_modules/.bin/json-server --static . data.json -m middleware.js --config json-server.json
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
