name: Cypress Tests2

on: [push]
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     
      
      - name: Checkout Cypress
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress

     # - name: Cypress
      #  uses: cypress-io/github-action@v2.9.7
      #  with:
       #   wait-on: "http://localhost:3000/"
          

      - name: Checkout App
        run: |
         npm install 
         npm start
         npm cypress-e2e

