name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest
   
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2.4.2
      with:
        path: ./frontend  
        
    - name: install npm
      run: | 
             cd frontend
             ls
             npm install
             npm start &


    - name: Cypress
      uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress
       path: ./cypress
    
    - name: cypress install npm 
      run: | 
             cd cypress
             ls
             npm install
             npx cypress run
             
    #- run: npm install
    #- run: npx cypress run

    - run: curl --fail --request GET --url "http://localhost:3000"

