name: Cypress Tests2

on: [push]
     
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress
      - run: npm run cypress-e2e
      
  build:
    needs: setup
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - run: |
          ./start.sh
          ./test.sh
        shell: bash
