
name: Cypress Tests2

on: [pull_request]

jobs:

 start:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Web
      uses: actions/checkout@v2.4.2
      with:
        path: ./frontend  
            
        
    - name: Web install npm
      run: | 
             cd frontend
             ls
             echo "This is the $MY_ENV_1 environment variable"
             npm install
             npm start &
             
    - name: Variables
      run: | 
             cd frontend
             ls
             echo "hola"
             echo "GO_VERSION=$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')" >> $GITHUB_ENV
             echo "MESSAGE= $(git log -1 --pretty=%B)"
             echo "BRANCH=$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')" >> $GITHUB_ENV
             echo "EMAIL=$(git log -1 --pretty=%ae)" >> $GITHUB_ENV
             echo "AUTHOR=$(git log -1 --pretty=%an)" >> $GITHUB_ENV
             echo "SHA=$(git log -1 --pretty=%H)" >> $GITHUB_ENV
             echo "REMOTE=$(git config --get remote.origin.url)" >> $GITHUB_ENV

    - name: Checkout Cypress
      uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress
       path: ./cypress
       
    
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
       working-directory: /home/runner/work/app/app/cypress
       record: true
       browser: chrome
       tag: ${{ github.event_name }}
       ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
      env:
        CI: true 
        COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
        COMMIT_INFO_BRANCH: ${{ env.BRANCH }}
        COMMIT_INFO_AUTHOR: ${{ env.AUTHOR }}
        COMMIT_INFO_SHA: ${{ github.event.pull_request.head.sha }}
        CYPRESS_RECORD_KEY: b4c9b2c8-be43-4a55-b893-66ebbd362b02
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        COMMIT_INFO_REMOTE: ${{ env.REMOTE }}

