
name: Cypress Tests2

on: [pull_request]

jobs:

 start:
    runs-on: ubuntu-latest
   
    steps:
    
    - name: Checkout Web
      uses: actions/checkout@v2.4.2
      with:
        path: ./frontend  
        
    - name: Web install npm
      run: | 
             cd frontend
             ls
             npm install
             npm start &
    - name: Checkout Cypress
      uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress
       path: ./cypress
    
    - name: Cypress install npm 
      run: | 
             cd cypress
             ls
             npm install
             
             
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
       working-directory: /home/runner/work/app/app/cypress
       record: true
       browser: chrome
       
      env:
          CYPRESS_RECORD_KEY: 86b28930-8548-45bf-9496-d464a69e822a
          COMMIT_INFO_BRANCH: ${{github.head_ref}}
          COMMIT_INFO_MESSAGE: ${{github.head_ref}}
          COMMIT_INFO_AUTHOR: ${{github.actor}}
          COMMIT_INFO_SHA: ${{github.head_ref}}
          COMMIT_INFO_REMOTE: ${{github.repositoryUrl}}

