name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest
    
    container: cypress/browsers:node12.18.3-chrome87-ff82
    
    steps:
    
    #- name: Checkout
    - uses: actions/checkout@v2.4.2
    - run: npm install
    - run: npm start &
    - run: curl ifconfig.me
    - run: curl --fail --request GET --url "http://localhost:3000"

    #- name: Cypress
    - uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress

    - uses: cypress-io/github-action@v2
      with:
        browser: chrome
        env: host=13.82.53.142,port=3000


