name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest
    steps:
    
    #- name: Checkout
    - uses: actions/checkout@v2.4.2
    - run: npm install
    - run: |
       npm start
       lt --port 3000 &
    
    #- name: Checkout Cypress
    - uses: actions/checkout@main
      with: 
         repository: rmhiguerey/cypress
         
    - run: npm install
    - run: npm run cypress-e2e
      
    #- name: Cypress
    #- uses: cypress-io/github-action@v2.9.7
     # with:
      #  install: true
      #  browser: chrome
      #  headless: true
        #config-file: cypress.json
        


