name: Cypress Tests2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    types: ["opened", "synchronize"]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          start: npm run start
          
      - name: Checkout
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress
          start: npm run cypress-e2e
          wait-on: 'http://localhost:3000'

      
