
name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest
    env:
      MY_ENV_1: My environment variable 1
      MY_ENV_2: My environment variable 2
   
    steps:
    
    - name: Checkout Web
      uses: actions/checkout@v2.4.2
      with:
        path: ./frontend  
            
        
    - name: Web install npm
      run: | 
             cd frontend
             ls
             echo "This is the $MY_ENV_1 environment variable"
             npm install
             npm start &
             
    - name: Variables
      run: | 
             cd frontend
             ls
             echo "hola"
             echo "GO_VERSION=$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')" >> $GITHUB_ENV
             echo BRANCH=$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')" >> $GITHUB_ENV
             echo MESSAGE="$(git log -1 --pretty=%B)" >> $GITHUB_ENV
             echo EMAIL="$(git log -1 --pretty=%ae)" >> $GITHUB_ENV
             echo AUTHOR="$(git log -1 --pretty=%an)" >> $GITHUB_ENV
             echo SHA="$(git log -1 --pretty=%H)" >> $GITHUB_ENV
             echo REMOTE="$(git config --get remote.origin.url)" >> $GITHUB_ENV

    - name: Checkout Cypress
      uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress
       path: ./cypress
       
    - name: Cypress install npm 
      run: | 
             cd cypress
             ls
             npm install
    
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
       working-directory: /home/runner/work/app/app/cypress
       #record: true
       browser: chrome
      env:
        COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
        COMMIT_INFO_BRANCH: ${{ github.head_ref }}
        COMMIT_INFO_SHA: ${{ github.sha }}
        CYPRESS_RECORD_KEY: b4c9b2c8-be43-4a55-b893-66ebbd362b02
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_INFO_REMOTE: https://github.com/rmhiguerey/app.git
        
    - name: Variables
      run: |
            echo ${{ env.GO_VERSION }}
            echo ${{ env.BRANCH }}
            echo ${{ env.MESSAGE }}
            echo ${{ env.EMAIL }}
            echo ${{ env.AUTHOR }}
            echo ${{ env.SHA }}
            echo ${{ env.REMOTE }}
