name: Cypress Tests2

on: [push]
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    
              
      - name: Checkout
        uses: actions/checkout@v2.4.2
        with: 
          run: npm install
      
      - name: Checkout cypress
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress

      - name: Cypress dependencies
        uses: cypress-io/github-action@v2.9.7
        with:
          runTest: false
        
      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        timeout-minutes: 30
        with:
          browser: chrome
          headless: true
          # we have already installed all dependencies above
          install: true
          start: npm run start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'

     
