name: Cypress Tests2

on: [pull_request]

jobs:

 start:
    runs-on: ubuntu-latest
   
    steps:
    
    - name: Checkout Web
      uses: actions/checkout@v2.4.2
      with:
        path: ./frontend  
        
    - name: Web install npm
      run: | 
             cd frontend
             ls
             npm install
             npm start &


    - name: Checkout Cypress
      uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress
       path: ./cypress
    
    - name: Cypress install npm 
      run: | 
             cd cypress
             ls
             npm install
             
    - name: Cypress.io
      uses: cypress-io/github-action@v2.9.7
      with:
       record: true
       browser: chrome
       
      env:
          CYPRESS_RECORD_KEY: bb5e29b2-35c0-4cef-a20d-5cf4b5257a27 
      
