name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest
   
    steps:
    
    #- name: Checkout
    - uses: actions/checkout@v2.4.2
      with:
        path: ./frontend
        
    - run: cd /frontend
    - run: npm install
    - run: npm start &
    - run: curl ifconfig.me


    #- name: Cypress
    - uses: actions/checkout@v2.4.2
      with:
       repository: rmhiguerey/cypress
       path: ./cypress
       
    #- run: npm install
    #- run: npx cypress run

    - run: curl --fail --request GET --url "http://localhost:3000"

