name: Cypress Tests2

on:
  workflow_dispatch:
  push:
    branches:
      - main
    types: ["opened", "synchronize"]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress


      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 30
        with:
          browser: chrome
          headless: true
          # we have already installed all dependencies above
          install: false
          start: npm run dev:unix
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
