name: Cypress Tests2

on: [push]
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     
      - name: Checkout App
        uses: actions/checkout@v2.4.2
      - run: npm install npm-run-parallel
      - run: npm-run-parallel start  
      
      - name: Checkout Cypress
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress
      - run: npm-run-parallel run cypress-e2e

