name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest     
    steps:
    
    #- name: Checkout
    - uses: actions/checkout@v2.4.2

    #- name: Cypress
    - uses: cypress-io/github-action@v2.9.7
      with:
        start: npm start
        install: true
        headless: true
 


