name: Cypress Tests2

on: [push]

jobs:

 start:
    runs-on: ubuntu-latest
    container: node:14.16.0
    steps:
    - run: node --version
    - run: npm --version
    #- name: Checkout
    - uses: actions/checkout@v2.4.2
    - run: npm install
    - run: node app.js&
    #- run: npm start
    
    #- name: Checkout Cypress
    - uses: actions/checkout@main
      with: 
         repository: rmhiguerey/cypress


    #- name: Cypress
    - uses: cypress-io/github-action@v2.9.7
      with:
        install: true
        browser: chrome
        headless: true
        config-file: cypress.json
        


