name: Cypress Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: ["opened", "synchronize"]
    
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
  call-workflow:
    uses: ./cypress/.github/workflows/main.yml
