name: Cypress Tests2

on: [push]
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress
      -  run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 30
        with:
          repository: ./rmhiguerey/cypress
          browser: chrome
          headless: true
          # we have already installed all dependencies above
          install: true
          start: npm run start
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
