name: Cypress Tests2

on: [push]
     
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@main
        with: 
          repository: rmhiguerey/cypress

      - name: Cypress run
        uses: cypress-io/github-action@v2
        timeout-minutes: 30
        with:
          project: app
          browser: chrome
          headless: true
          # we have already installed all dependencies above
          install: true
          #start: npm start
          command: npm run cypress-e2e
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
